- src/ui-config/networks.ts
https://blog.polygon.technology/polygon-rpc-gateway-will-provide-a-free-high-performance-connection-to-the-polygon-pos-blockchain-df148958d418
> fix: use aggregated polygon rpc

- src/components/TxConfirmationView/NetworkMismatch/index.tsx
- src/libs/pool-data-provider/providers/static-pool-data-provider.tsx
- src/modules/deposit/components/DepositDashboardTable/DepositMobileCard.tsx
- src/modules/repay/screens/RepayAmountWithSelect/index.tsx
- src/modules/repay/screens/RepayMain/index.tsx
- removes gnosis from providers known to not support polygon
- temporary fixes incentives for assets that have no registered emission. Will be reverted once the aip is executed.
- disables repayWithCollateral on the ui for assets with less then 1M liquidity in uni v2 pools. This is to avoid accidental high slippage repays.
> fix: batch of fixes

- .github/workflows/main.yml
> fix: correct number

- src/components/TxEstimationEditor/EditorModal/index.tsx
- src/libs/hooks/use-get-gas-prices.tsx
gasnow is sunsetting on 15.
this pr replaces it with the paraswap gas api
> fix: replace gasnow with paraswap api

- .github/ISSUE_TEMPLATES/1.bug.md
- .github/ISSUE_TEMPLATES/2.feature.md
- highly inspired by https://github.com/mui-org/material-ui/tree/master/.github/ISSUE_TEMPLATE because they are crazy good :shrug:
- relates to #66
> chore: add issue templates

- package-lock.json
- package.json
- src/components/wrappers/CurrencyScreenWrapper/CurrencyOverview/index.tsx
- src/components/wrappers/CurrencyScreenWrapper/CurrencyOverview/messages.ts
- src/libs/caching-server-data-provider/hooks/use-cached-protocol-data.tsx
- src/libs/pool-data-provider/hooks/use-v2-protocol-data-with-rpc.tsx
- src/libs/use-asset-swap/useSwap.ts
- src/modules/asset-swap/screens/AssetSwapMain/index.tsx
- src/modules/borrow/screens/BorrowConfirmation/index.tsx
- src/modules/borrow/screens/BorrowMain/index.tsx
- src/modules/dashboard/screens/Dashboard/index.tsx
- src/modules/deposit/screens/DepositMain/index.tsx
- src/modules/markets/screens/Markets/index.tsx
- src/modules/reserve-overview/components/ReserveInformation/index.tsx
- src/modules/reserve-overview/components/ReserveInformation/messages.ts
- src/modules/swap/SwapBorrowRateModeConfirmation/index.tsx
Use updated Reserve and UserReserve types with APY/APR fields in place of liquidityRate and borrowRate
Add a row on the reserve overview page to display the deposit and borrow APR
TO-DO: Add translations for deposit and borrow APR
> feat: add aprs

- src/components/menu/AddressInfo/index.tsx
- src/components/menu/AddressInfo/style.ts
- src/libs/hooks/use-get-ens-name.tsx
If an address has an associated ens name on Ethereum mainnet, display in the address info panel in the top right corner
> feat: add ens name

- src/components/TxConfirmationView/NetworkMismatch/index.tsx
> feat: allow switching from any, to any network via ui

- src/modules/deposit/components/DepositDashboardTable/DepositItem.tsx
- src/modules/deposit/components/DepositDashboardTable/DepositMobileCard.tsx
before this pr the withdraw button for amm reserves would be grayed out
mock user to test: 0xdad4c11e8cc6a5c37808d3b31b3b284809f702d1
> fix: allow users to withdraw on frozen reserves

- src/helpers/lp-tokens.ts
closes https://github.com/aave/aave-ui/issues/166
> fix broken link on uniswap v2 pools

- README.md
- VERIFICATION.md
Explain process of verifying contract addresses for interacting with the Aave protocol
> feat: add verification doc

- package-lock.json
- src/modules/markets/screens/Markets/index.tsx
> feat: dont show frozen reserves on markets page

- src/components/AMPLWarning/index.tsx
- src/components/AMPLWarning/messages.ts
Added a link to Ampleforth lending borrowing FAQ which describes AMPL lending borrowing behavior and commonly asked questions
Updated message:
> Ampleforth is an asset affected by rebasing. Visit the documentation or Ampleforth's FAQ to learn more.
> Updated info message in the AMPL market

- package-lock.json
- package.json
- src/ui-config/markets/index.ts
- src/ui-config/networks.ts
Add config for ETH rinkeby market and update
> feat: add eth rinkeby market

- package-lock.json
- package.json
- src/components/TxConfirmationView/index.tsx
- Disable request for permit if approvalTx is not required
- Use updated contract helper for repayWithATokens()
> Fix: repay with atokens

- package-lock.json
- package.json
userSummary was using the reserve stableRate opposed to the users stable rate which will result in slightly different results
> fix: use correct stable rate in userSummary

- src/libs/web3-data-provider/provider.tsx
previously it was set to the first market network
> fix: when no preferred network is set, current market network is preferred

- src/components/DepositBorrowTopPanel/index.tsx
- src/components/HealthFactor/index.tsx
- src/components/HelpModal/HealthFactorHelpModal/HALNotificationIcon.tsx
- src/components/HelpModal/HealthFactorHelpModal/images/bell.svg
- src/components/HelpModal/HealthFactorHelpModal/images/bellGray.svg
- src/components/HelpModal/HealthFactorHelpModal/images/bellGrayDark.svg
- src/components/HelpModal/HealthFactorHelpModal/index.tsx
- src/components/HelpModal/HealthFactorHelpModal/messages.ts
- src/components/HelpModal/HealthFactorHelpModal/style.ts
- src/components/HelpModal/HelpModalWrapper/index.tsx
- src/components/HelpModal/types.ts
- src/components/TextWithModal/index.tsx
- src/components/TextWithModal/style.ts
- src/modules/dashboard/screens/Dashboard/index.tsx
- src/modules/reserve-overview/components/UserInformation/index.tsx
- src/translations/cn.json
- src/translations/default.json
- src/translations/en.json
- src/translations/es.json
- src/translations/fr.json
- src/translations/it.json
- src/translations/ja.json
- src/translations/ko.json
- src/translations/pt.json
- src/translations/tr.json
- src/translations/vi.json
This PR adds HAL Notification integration to Aave.
The DAO voted on this proposal here:
https://snapshot.org/#/aave.eth/proposal/0xa730caeec3c28e014ff456b454186ef41c6c1f382cf0a7caa3d99c4ae16c8318
Full discussion on the forum community: 
https://governance.aave.com/t/add-hal-push-in-notification-system-on-aave/6512
Example Screenshot of UI Change - see forums above for additional information:
> Feat: HAL Integration - Add HAL Notification Icon

- src/components/basic/RiskBar/index.tsx
- src/libs/use-asset-swap/useSwap.ts
- src/modules/asset-swap/helpers.tsx
- src/modules/deposit/components/SupplyAssetsTable/index.tsx
- src/modules/deposit/screens/DepositConfirmation/index.tsx
- src/modules/history/screens/History/index.tsx
- src/modules/repay/helpers.tsx
- src/modules/repay/screens/RepayAmount/index.tsx
- src/modules/repay/screens/RepayConfirmation/index.tsx
Several bug fixes:
- Use formatted values for previously overwritten fields which were missed (fixes zero HF error)
- Match BorrowConfirmation logic where health factor is locked after executing the transaction. Without this the new health factor will simulate the deposit happening again
- Factor isolationMode into new health factor calculation on deposit screen
- Fix bug with repay health factor caused by change to formatted priceInMarketReferenceCurrency
> fix: health factor bugs

- package-lock.json
- package.json
update for https://github.com/aave/aave-utilities/pull/295/files#diff-b56f6e564ef0efc6915d2e1054c3f7dcf12c8220d80de20043c67741204d7cefR35
> fix: update paraswap calldata mappings

- .github/workflows/deploy.yml
- .github/workflows/deploy_prod.yml
- scripts/update-cloudflare.js
Change `app.aave.com` to `classic.aave.com`
> Change production domain for v3 release

- src/ui-config/markets/index.ts
update the weth gateway contracts to the new ones.
> chore: update weth gateway contract
